### ISSUE TITLE
Seedlings roadmap

### ISSUE THREAD

**Issue by dancgray** [totara/seedlings#5]
Hi, Totara/Seedlings looks really good. 

What's the roadmap for seedlings updates? Totara is now on v2.9 and there has not been an update to seedlings since Nov 2014, as far as I can tell ;)

Would be really good to see seedlings upto date with totara.
Thanks
Dan

**Comment by simoncoggins** [comment]
Hi Dan,
We're not going to be continuing the Seedlings releases, but we are working on a new approach which achieve the same goal as Seedlings (giving access to new functionality before the stable release is out), but we're not quite ready to announce that yet. We'll be releasing it a couple of months after the next major release (before the end of the year).
Simon
