### ISSUE TITLE
Enable program completion editor option - NOT AVAILABLE

### ISSUE THREAD

**Issue by mselavarasan** [totara/seedlings#6]
Totara Seedlings 2.7 doesn't have "Enable Program Completion Editor Option" under "Site administration > Advanced features"
Any Idea how to make enable this feature in Seedlings 2.7?
Thanks

**Comment by simoncoggins** [comment]
The program and certification completion editor tool was released in Totara versions 2.5.36, 2.6.29, 2.7.12 and 2.9.4. To be able to use the tool you must be on one of these versions (or higher). Totara Seedlings 2.7 does not include the editor, you would need to subscribe to get updates that include that feature.
